name: Koyeb Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Koyeb Deployment
        run: |
          curl -X POST "https://app.koyeb.com/v1/apps/token_eshop_advpro/deployments" \
          -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{}'